"""
Server-side white-label PDF report generation (fpdf2 — pure Python, no system
deps, safe on serverless hosts like Vercel).

Layout (A4, mm):
  - White-label header: agency logo + agency name, site domain, generated date
  - KPI cards: health score, delta, open issues, fixes deployed, leads
  - SEO Health Score trend line chart (from crawl history)
  - Google Search Console block: clicks/impressions/CTR/position KPIs, trend
    chart, and top queries table (only when connected)
  - Fixes deployed timeline and open-issue breakdown tables
  - Footer on every page: agency name, page number, "Generated by SEOOps"
"""
import base64
import io
from datetime import datetime
from typing import Any, Dict, List, Optional

from fpdf import FPDF

# Palette (matches the frontend)
PRIMARY = (99, 102, 241)
DARK = (30, 41, 59)
MUTED = (100, 116, 139)
LIGHT_FILL = (241, 245, 249)
TEAL = (6, 182, 212)
GREEN = (52, 211, 153)
AMBER = (251, 191, 36)
ROSE = (244, 63, 94)

PAGE_W = 210.0
MARGIN = 14.0
CONTENT_W = PAGE_W - 2 * MARGIN  # 182mm


def _txt(value: Any) -> str:
    """Latin-1 safe text for the built-in core fonts."""
    if value is None:
        return ""
    return str(value).encode("latin-1", "replace").decode("latin-1")


def _shorten(value: Any, limit: int) -> str:
    text = _txt(value)
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "..."


def _parse_data_url(data_url: Optional[str]) -> Optional[io.BytesIO]:
    """Turn 'data:image/png;base64,...' into a BytesIO, or None."""
    if not data_url:
        return None
    try:
        header, _, b64 = data_url.partition(",")
        if "base64" not in header:
            return None
        return io.BytesIO(base64.b64decode(b64))
    except Exception:
        return None


def _image_size(raw: bytes) -> tuple[int, int]:
    """Read width/height for PNG or JPEG headers without extra dependencies."""
    if raw[:8] == b"\x89PNG\r\n\x1a\n" and len(raw) >= 24:
        w = int.from_bytes(raw[16:20], "big")
        h = int.from_bytes(raw[20:24], "big")
        return (w, h)
    if raw[:2] == b"\xff\xd8":
        i = 2
        while i < len(raw) - 9:
            if raw[i] != 0xFF:
                i += 1
                continue
            marker = raw[i + 1]
            if marker in (0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF):
                h = int.from_bytes(raw[i + 5 : i + 7], "big")
                w = int.from_bytes(raw[i + 7 : i + 9], "big")
                return (w, h)
            seg_len = int.from_bytes(raw[i + 2 : i + 4], "big")
            i += 2 + seg_len
    return (0, 0)


class _ReportPDF(FPDF):
    def __init__(self, agency_name: str):
        super().__init__(format="A4", unit="mm")
        self.agency_name = _txt(agency_name or "SEOOps")
        self.set_auto_page_break(auto=True, margin=18)

    def footer(self):
        if self.page_no() == 1:
            return
        self.set_y(-14)
        self.set_font("helvetica", "", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 6, self.agency_name, align="L")
        self.cell(0, 6, f"Page {self.page_no()}", align="C")
        self.cell(0, 6, "Generated by SEOOps", align="R")


def _section_header(pdf: FPDF, title: str, color=PRIMARY):
    pdf.ln(3)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(*DARK)
    pdf.set_fill_color(*color)
    pdf.rect(MARGIN, pdf.get_y(), 1.6, 6.4, style="F")
    pdf.set_x(MARGIN + 4)
    pdf.cell(CONTENT_W - 4, 6.4, _txt(title), align="L")
    pdf.ln(8.5)
    pdf.set_x(MARGIN)


def _kpi_cards(pdf: FPDF, report: Dict[str, Any]):
    score = report.get("current_score")
    delta = report.get("score_delta")
    cards = [
        ("Health Score", f"{score if score is not None else '--'}/100", PRIMARY),
        ("Score Delta", f"+{delta}" if delta is not None and delta >= 0 else (str(delta) if delta is not None else "--"), GREEN if (delta or 0) >= 0 else ROSE),
        ("Open Issues", str(report.get("open_issues", 0)), AMBER),
        ("Fixes Deployed", str(report.get("approved_fixes", 0)), TEAL),
        ("Leads Captured", str(report.get("leads_captured", 0)), MUTED),
    ]
    card_w = (CONTENT_W - 4 * 3) / 5
    x0 = MARGIN
    y0 = pdf.get_y()
    for i, (label, value, color) in enumerate(cards):
        x = x0 + i * (card_w + 3)
        pdf.set_fill_color(*LIGHT_FILL)
        pdf.rect(x, y0, card_w, 22, style="F")
        pdf.set_fill_color(*color)
        pdf.rect(x, y0, card_w, 1.4, style="F")
        pdf.set_xy(x, y0 + 5)
        pdf.set_font("helvetica", "", 8)
        pdf.set_text_color(*MUTED)
        pdf.cell(card_w, 5, _txt(label), align="C")
        pdf.set_xy(x, y0 + 11)
        pdf.set_font("helvetica", "B", 16)
        pdf.set_text_color(*DARK)
        pdf.cell(card_w, 8, _txt(value), align="C")
    pdf.set_y(y0 + 26)


def _line_chart(
    pdf: FPDF,
    values: List[float],
    labels: List[str],
    x: float,
    y: float,
    w: float,
    h: float,
    color=PRIMARY,
    y_min: Optional[float] = None,
    y_max: Optional[float] = None,
    fill_below: bool = True,
):
    if not values:
        return
    lo = y_min if y_min is not None else min(values)
    hi = y_max if y_max is not None else max(values)
    if hi == lo:
        hi = lo + 1
    pad = 6
    plot_w = w - pad
    plot_h = h - pad

    # grid + y labels (pdf.text keeps the cursor still - never triggers page breaks)
    pdf.set_font("helvetica", "", 7)
    pdf.set_text_color(*MUTED)
    for i in range(5):
        gy = y + plot_h - (plot_h * i / 4)
        pdf.set_draw_color(226, 232, 240)
        pdf.set_line_width(0.2)
        pdf.line(x + pad, gy, x + w, gy)
        val = lo + (hi - lo) * i / 4
        pdf.text(x, gy - 1, f"{round(val)}")

    pts = []
    n = len(values)
    for i, v in enumerate(values):
        px = x + pad + (plot_w * i / max(1, n - 1))
        py = y + plot_h - (plot_h * (v - lo) / (hi - lo))
        pts.append((px, py))

    # fill below the line
    if fill_below:
        pdf.set_fill_color(color[0], color[1], color[2])
        pdf.set_draw_color(color[0], color[1], color[2])
        pdf.set_line_width(0.3)
        for i in range(len(pts) - 1):
            x1, y1 = pts[i]
            x2, y2 = pts[i + 1]
            pdf.polygon([(x1, y1), (x2, y2), (x2, y + plot_h), (x1, y + plot_h)], style="DF")

    # line
    pdf.set_draw_color(*color)
    pdf.set_line_width(0.8)
    for i in range(len(pts) - 1):
        pdf.line(pts[i][0], pts[i][1], pts[i + 1][0], pts[i + 1][1])

    # points
    pdf.set_fill_color(*color)
    for px, py in pts:
        pdf.ellipse(px - 1, py - 1, 2, 2, style="F")

    # x labels (first / last)
    pdf.set_text_color(*MUTED)
    pdf.set_font("helvetica", "", 7)
    if n > 1:
        pdf.text(x + pad, y + plot_h + 3, _shorten(labels[0], 18))
        pdf.text(x + w - 30, y + plot_h + 3, _shorten(labels[-1], 18))


def _date_label(iso: Optional[str]) -> str:
    if not iso:
        return ""
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%b %d")
    except Exception:
        return _shorten(iso, 12)


def _data_table(pdf: FPDF, headers: List[str], widths: List[float], rows: List[List[str]], row_h: float = 6):
    pdf.set_font("helvetica", "B", 8)
    pdf.set_fill_color(238, 242, 255)
    pdf.set_text_color(*DARK)
    x0 = MARGIN
    y0 = pdf.get_y()
    for i, (header, wd) in enumerate(zip(headers, widths)):
        pdf.set_xy(x0 + sum(widths[:i]), y0)
        pdf.cell(wd, row_h, _txt(header), fill=True)
    pdf.ln(row_h)

    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(*DARK)
    for r, row in enumerate(rows):
        y = pdf.get_y()
        if y + row_h > 279:
            pdf.add_page()
            y = pdf.get_y()
        if r % 2 == 1:
            pdf.set_fill_color(*LIGHT_FILL)
            fill = True
        else:
            pdf.set_fill_color(255, 255, 255)
            fill = True
        for i, (cell, wd) in enumerate(zip(row, widths)):
            pdf.set_xy(x0 + sum(widths[:i]), y)
            pdf.cell(wd, row_h, _shorten(cell, int(wd * 0.9)), fill=fill)
        pdf.ln(row_h)
    pdf.ln(2)


def build_whitelabel_pdf(
    report: Dict[str, Any],
    agency_name: str,
    logo_data_url: Optional[str] = None,
) -> bytes:
    pdf = _ReportPDF(agency_name)
    pdf.set_margins(MARGIN, MARGIN, MARGIN)
    pdf.add_page()

    # ---- White-label header -------------------------------------------------
    logo_raw = _parse_data_url(logo_data_url)
    logo_x = MARGIN
    logo_y = 14
    title_x = MARGIN
    if logo_raw is not None:
        raw = logo_raw.getvalue()
        iw, ih = _image_size(raw)
        logo_w = 42.0
        if iw and ih:
            logo_h = logo_w * ih / iw
            if logo_h > 18:
                logo_w = logo_w * 18 / logo_h
                logo_h = 18
        else:
            logo_h = 14
        try:
            pdf.image(io.BytesIO(raw), x=logo_x, y=logo_y, w=logo_w)
            title_x = logo_x + logo_w + 5
        except Exception:
            logo_raw = None

    pdf.set_xy(title_x, 15)
    pdf.set_font("helvetica", "B", 19)
    pdf.set_text_color(*DARK)
    pdf.cell(CONTENT_W - (title_x - MARGIN), 9, _txt(agency_name or "SEOOps"), align="L")
    pdf.set_xy(title_x, 25)
    pdf.set_font("helvetica", "B", 13)
    pdf.set_text_color(*PRIMARY)
    pdf.cell(CONTENT_W - (title_x - MARGIN), 7, "SEO Performance Report", align="L")

    pdf.set_xy(MARGIN, 34)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(CONTENT_W, 5, _txt(report.get("domain", "")), align="L")
    pdf.set_xy(MARGIN, 39.5)
    pdf.cell(CONTENT_W, 5, f"Generated {datetime.utcnow().strftime('%B %d, %Y')}", align="L")
    if report.get("industry"):
        pdf.set_xy(MARGIN, 45)
        pdf.cell(CONTENT_W, 5, f"Industry: {_txt(report['industry'])}", align="L")

    pdf.set_draw_color(*PRIMARY)
    pdf.set_line_width(0.6)
    pdf.line(MARGIN, 51, PAGE_W - MARGIN, 51)

    pdf.set_y(56)

    # ---- KPI cards ----------------------------------------------------------
    _kpi_cards(pdf, report)

    # ---- Score trend --------------------------------------------------------
    _section_header(pdf, "SEO Health Score Trend")
    score_history = report.get("score_history", [])
    if score_history:
        values = [p["score"] for p in score_history]
        labels = [_date_label(p["date"]) for p in score_history]
        chart_y = pdf.get_y()
        _line_chart(pdf, values, labels, MARGIN, chart_y, CONTENT_W, 52)
        pdf.set_y(chart_y + 58)  # 52 chart + 6 label space
    else:
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(CONTENT_W, 5, "No completed scans yet - run a scan to start the trend.", align="L")
        pdf.ln(4)

    # ---- Google Search Console ----------------------------------------------
    gsc = report.get("gsc", {})
    metrics = gsc.get("metrics", [])
    if gsc.get("connected") and metrics:
        _section_header(pdf, "Google Search Console - Search Performance", TEAL)
        tot_clicks = sum(m["clicks"] for m in metrics)
        tot_imps = sum(m["impressions"] for m in metrics)
        avg_pos = round(sum(m["position"] for m in metrics) / len(metrics), 1) if metrics else 0
        avg_ctr = round(sum(m["ctr"] for m in metrics) / len(metrics), 4) if metrics else 0
        chips = [
            ("Clicks", f"{tot_clicks:,}", TEAL),
            ("Impressions", f"{tot_imps:,}", PRIMARY),
            ("Avg. CTR", f"{avg_ctr * 100:.1f}%", GREEN),
            ("Avg. Position", f"{avg_pos:.1f}", AMBER),
        ]
        chip_w = (CONTENT_W - 3 * 4) / 4
        y0 = pdf.get_y()
        for i, (label, value, color) in enumerate(chips):
            x = MARGIN + i * (chip_w + 4)
            pdf.set_fill_color(*LIGHT_FILL)
            pdf.rect(x, y0, chip_w, 18, style="F")
            pdf.set_fill_color(*color)
            pdf.rect(x, y0, chip_w, 1.2, style="F")
            pdf.set_xy(x, y0 + 4)
            pdf.set_font("helvetica", "", 8)
            pdf.set_text_color(*MUTED)
            pdf.cell(chip_w, 4.5, label, align="C")
            pdf.set_xy(x, y0 + 9)
            pdf.set_font("helvetica", "B", 13)
            pdf.set_text_color(*DARK)
            pdf.cell(chip_w, 6, _txt(value), align="C")
        pdf.set_y(y0 + 23)

        # clicks (line) + impressions (bars)
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(*DARK)
        pdf.cell(CONTENT_W, 5, "Clicks & Impressions (last 30 days)", align="L")
        pdf.ln(7)
        chart_y = pdf.get_y()
        imps = [float(m["impressions"]) for m in metrics]
        clicks = [float(m["clicks"]) for m in metrics]
        dates = [_date_label(m["date"]) for m in metrics]

        lo, hi = 0, max(imps) or 1
        pad = 8
        plot_w = CONTENT_W - pad
        plot_h = 44
        # bars
        n = len(imps)
        bar_w = plot_w / max(1, n) * 0.55
        pdf.set_fill_color(199, 210, 254)
        for i, v in enumerate(imps):
            bx = MARGIN + pad + (plot_w * i / max(1, n - 1))
            bh = plot_h * v / hi
            pdf.rect(bx - bar_w / 2, chart_y + plot_h - bh, bar_w, bh, style="F")
        # clicks line
        _line_chart(
            pdf, clicks, dates, MARGIN, chart_y, CONTENT_W, plot_h,
            color=TEAL, y_min=0, y_max=max(clicks) or 1, fill_below=False,
        )
        pdf.set_y(chart_y + plot_h + 12)

        # top queries
        top_queries = gsc.get("top_queries", [])[:10]
        if top_queries:
            pdf.ln(2)
            pdf.set_font("helvetica", "B", 9)
            pdf.set_text_color(*DARK)
            pdf.cell(CONTENT_W, 5, "Top Search Queries", align="L")
            pdf.ln(7)
            rows = [
                [q["query"], str(q["clicks"]), f"{q['impressions']:,}", f"{q['ctr'] * 100:.1f}%", f"{q['position']:.1f}"]
                for q in top_queries
            ]
            _data_table(
                pdf,
                ["Query", "Clicks", "Impressions", "CTR", "Position"],
                [86, 24, 30, 20, 22],
                rows,
            )
    elif gsc.get("connected"):
        _section_header(pdf, "Google Search Console", TEAL)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(CONTENT_W, 5, "Connected, but no metrics synced yet - data appears after the next daily sync.", align="L")
        pdf.ln(4)
    else:
        _section_header(pdf, "Google Search Console", TEAL)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(
            CONTENT_W, 5,
            "Not connected. Connect Google Search Console from the report page to include real click and impression data.",
            align="L",
        )
        pdf.ln(4)

    # ---- Fixes deployed -----------------------------------------------------
    _section_header(pdf, "Fixes Deployed")
    fixes = report.get("fixes_timeline", [])
    if fixes:
        rows = []
        for fix in fixes:
            rows.append([
                _date_label(fix.get("approved_at")),
                _shorten(fix.get("page_url", ""), 50),
                _shorten(fix.get("issue_type", ""), 24),
                _shorten(fix.get("applied_title") or fix.get("applied_meta") or "Applied", 38),
            ])
        _data_table(
            pdf,
            ["Date", "Page", "Issue Type", "Fix Applied"],
            [24, 62, 38, 58],
            rows,
        )
    else:
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(CONTENT_W, 5, "No fixes deployed yet. Approve AI fix suggestions to track them here.", align="L")
        pdf.ln(4)

    # ---- Open issues --------------------------------------------------------
    _section_header(pdf, "Open Issues by Type")
    breakdown = report.get("issue_breakdown", [])
    if breakdown:
        rows = [
            [row["issue_type"], row["severity"].capitalize(), str(row["count"])]
            for row in breakdown
        ]
        _data_table(pdf, ["Issue Type", "Severity", "Count"], [110, 40, 32], rows)
    else:
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(CONTENT_W, 5, "No open issues. ", align="L")
        pdf.ln(4)

    # ---- Closing line -------------------------------------------------------
    pdf.ln(6)
    pdf.set_draw_color(*PRIMARY)
    pdf.set_line_width(0.6)
    pdf.line(MARGIN, pdf.get_y(), PAGE_W - MARGIN, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(CONTENT_W, 5, f"Prepared for {_txt(report.get('domain', ''))} by {_txt(agency_name or 'SEOOps')}. Confidential.", align="C")

    return bytes(pdf.output())  # fpdf2 output() returns a bytearray; FastAPI needs bytes
